# Generated by Django 3.0.1 on 2019-12-28 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_newuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewUser',
        ),
    ]
