# Generated by Django 3.0.1 on 2019-12-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='owner',
        ),
        migrations.AddField(
            model_name='post',
            name='owner_id',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
