# Generated by Django 3.0.1 on 2019-12-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_user', models.IntegerField(max_length=255)),
                ('received_user', models.IntegerField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('connected_date', models.DateTimeField()),
                ('request_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
