# Generated by Django 3.0.1 on 2019-12-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_user', models.IntegerField()),
                ('received_user', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='friends',
            name='request_date',
        ),
        migrations.AlterField(
            model_name='friends',
            name='received_user',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='friends',
            name='requested_user',
            field=models.IntegerField(),
        ),
    ]
